trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  MAVEN_VERSION: '3.8.1'
  JAVA_VERSION: '1.8'

stages:
- stage: Build
  jobs:
  - job: Build_Job
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.8'
        jdkArchitectureOption: 'x64'
        goals: 'clean package'
    
    - script: |
        ls $(Build.SourcesDirectory)/target
      displayName: 'View files after build'
    
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)/target'
        Contents: '*.jar'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

- stage: Deploy
  dependsOn: Build
  jobs:
  - job: Deploy_Job
    steps:
    - download: current
      artifact: drop
      
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'devops-sample-serviceconnection'
        appType: 'webApp'
        WebAppName: 'devops-sample'
        packageForLinux: '$(Pipeline.Workspace)/drop/*.jar'
